var firstname="thamannaa";
console.log(firstname);
document.getElementById("name").innerHTML=firstname;
var secondname=" roshan";
console.log(secondname);
document.getElementById("name2").innerHTML=secondname;
var fname=firstname.concat(secondname);
console.log(fname);
document.getElementById("fullname").innerHTML=fname;
var n1=15;
var n2=20;
var sum=n1+n2;
console.log(sum);
document.getElementById("summ").innerHTML=sum;
var replacename=fname.replace("thamannaa","coder");
console.log(replacename);
document.getElementById("rname").innerHTML=replacename;
var n3=7800;
var n4=78;
var subtraction=n3-n4;
console.log(subtraction);
document.getElementById("sub").innerHTML=subtraction;